version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
      args:
        # Use 163 mirror by default to mitigate Docker Hub timeouts
        BASE_PY_IMAGE: hub-mirror.c.163.com/library/python:3.11-slim
        # Optional corporate proxies (uncomment and set if needed)
        # HTTP_PROXY: ${HTTP_PROXY}
        # HTTPS_PROXY: ${HTTPS_PROXY}
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=sqlite:///./data/app.db
      - ADMIN_INITIAL_PASSWORD=${ADMIN_INITIAL_PASSWORD}
      - SECRET_KEY=${SECRET_KEY}
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASS=${SMTP_PASS}
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: ./web
      dockerfile: Dockerfile.frontend
      args:
        BASE_NODE_IMAGE: hub-mirror.c.163.com/library/node:18-alpine
        BASE_NODE_IMAGE_RUNTIME: hub-mirror.c.163.com/library/node:18-alpine
        # Optional corporate proxies (uncomment and set if needed)
        # HTTP_PROXY: ${HTTP_PROXY}
        # HTTPS_PROXY: ${HTTPS_PROXY}
    ports:
      - "3000:3000"
    environment:
      - BACKEND_URL=http://backend:8000
      - NODE_ENV=production
    depends_on:
      - backend
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - frontend
      - backend
    restart: unless-stopped

volumes:
  data:
