"""Add APIKey model for Pool API authentication

Revision ID: add_pool_api_keys
Revises: add_workspace_and_org_fields
Create Date: 2025-11-08 16:49:33.230915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "add_pool_api_keys"
down_revision = "add_workspace_and_org_fields"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pool_api_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key_hash', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pool_api_keys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pool_api_keys_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_pool_api_keys_key_hash'), ['key_hash'], unique=True)
        batch_op.create_index('ix_api_key_active', ['is_active', 'key_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pool_api_keys', schema=None) as batch_op:
        batch_op.drop_index('ix_api_key_active')
        batch_op.drop_index(batch_op.f('ix_pool_api_keys_key_hash'))
        batch_op.drop_index(batch_op.f('ix_pool_api_keys_is_active'))

    op.drop_table('pool_api_keys')
    # ### end Alembic commands ###

