"""Add workspace_id and organization_id to MotherTeam

Revision ID: add_workspace_and_org_fields
Revises: add_mother_group_settings
Create Date: 2025-11-08 16:38:29.140856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "add_workspace_and_org_fields"
down_revision = "add_mother_group_settings"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # 只保留 MotherTeam 相关的变更，移除其他表的操作
    with op.batch_alter_table('mother_teams', schema=None) as batch_op:
        batch_op.add_column(sa.Column('workspace_id', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('organization_id', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_mother_teams_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_mother_teams_workspace_id'), ['workspace_id'], unique=True)
        batch_op.create_index('ix_org_id', ['organization_id'], unique=False)
        batch_op.create_index('ix_workspace_id', ['workspace_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mother_teams', schema=None) as batch_op:
        batch_op.drop_index('ix_workspace_id')
        batch_op.drop_index('ix_org_id')
        batch_op.drop_index(batch_op.f('ix_mother_teams_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_mother_teams_organization_id'))
        batch_op.drop_column('updated_at')
        batch_op.drop_column('organization_id')
        batch_op.drop_column('workspace_id')
    # ### end Alembic commands ###

