'use client'

import type { AdminState } from '@/store/admin/types'

export const initialAdminState: AdminState = {
  authenticated: true,
  loginPassword: '',
  loginLoading: false,
  loginError: '',
  showPassword: false,
  mothers: [],
  mothersPage: 1,
  mothersPageSize: 20,
  mothersTotal: 0,
  mothersInitialized: false,
  mothersLoading: false,
  auditLogs: [],
  bulkHistory: [],
  stats: null,
  serviceStatus: {
    backend: 'unknown',
    lastCheck: null,
    db: undefined,
  },
  auditPage: 1,
  auditPageSize: 50,
  auditTotal: 0,
  auditInitialized: false,
  bulkHistoryPage: 1,
  bulkHistoryPageSize: 50,
  bulkHistoryTotal: 0,
  bulkHistoryInitialized: false,
  loading: false,
  statsLoading: false,
  currentTab: 'mothers',
  searchTerm: '',
  filterStatus: 'all',
  sortBy: 'created_at',
  sortOrder: 'desc',
  autoRefresh: false,
  error: null,
  codeCount: 10,
  codePrefix: '',
  codeLifecyclePlan: 'monthly',
  codeSwitchLimit: 3,
  codeSkuSlug: '',
  codeSkus: [],
  generatedCodes: [],
  generateLoading: false,
  showGenerated: false,
  codesStatusMother: '',
  codesStatusTeam: '',
  codesStatusBatch: '',
}
