// This file is intended to be generated by `pnpm gen:api-types` from the backend OpenAPI schema.
// Temporary placeholder to allow imports before the first generation.
// After generation, these placeholders will be replaced by exact types and enums.

// Minimal enums to start aligning types; replace with generated ones.
export enum InviteStatus {
  pending = 'pending',
  sent = 'sent',
  accepted = 'accepted',
  failed = 'failed',
  cancelled = 'cancelled',
}

export enum CodeStatus {
  unused = 'unused',
  used = 'used',
  expired = 'expired',
  blocked = 'blocked',
}

export enum MotherStatus {
  active = 'active',
  invalid = 'invalid',
  disabled = 'disabled',
}

// Generic paginated response (placeholder; replaced after generation)
export interface PaginationMeta {
  page?: number
  page_size?: number
  total?: number
}

export type PaginatedResponse<T> = {
  items?: T[]
  pagination?: PaginationMeta
}

// -------------------- Shared DTOs (placeholder approximations) --------------------

export interface PoolGroupSummary {
  id: number
  name: string
  description?: string | null
  is_active: boolean
  created_at?: string
}

export interface PoolGroupSettingsPayload {
  team_template?: string | null
  child_name_template?: string | null
  child_email_template?: string | null
  email_domain?: string | null
  is_active?: boolean
}

export interface MotherTeamSummary {
  team_id: string
  team_name?: string
  is_enabled: boolean
  is_default: boolean
}

export interface InviteListItem {
  id: number
  email: string
  status: InviteStatus
  team_id?: string
  team_name?: string
  invited_at: string
  redeemed_at?: string
  code_used?: string
}

export interface RedeemCodeItem {
  id: number
  code: string
  batch_id?: string
  is_used: boolean
  status?: CodeStatus
  expires_at?: string
  created_at: string
  used_by?: string
  used_at?: string
  mother_id?: number
  mother_name?: string
  team_id?: string
  team_name?: string
  invite_status?: string
  lifecycle_plan?: string
  lifecycle_started_at?: string
  lifecycle_expires_at?: string
  switch_limit?: number
  switch_count?: number
  active?: boolean
  sku_slug?: string
  refresh_limit?: number | null
  refresh_used?: number | null
  refresh_cooldown_until?: string | null
  bound_email?: string | null
}

export interface MotherAccountSummary {
  id: number
  name: string
  status: MotherStatus
  seat_limit: number
  seats_used: number
  token_expires_at?: string
  notes?: string
  teams: MotherTeamSummary[]
}

export interface AuditLogEntry {
  id: number
  actor: string
  action: string
  target_type?: string | null
  target_id?: string | null
  payload_redacted?: string | null
  ip?: string | null
  ua?: string | null
  created_at?: string | null
}

export interface BulkOperationLogEntry {
  id: number
  operation_type: string
  actor: string
  total_count?: number | null
  success_count?: number | null
  failed_count?: number | null
  metadata: Record<string, unknown>
  created_at?: string | null
}

export interface DashboardStats {
  total_codes: number
  used_codes: number
  pending_invites: number
  successful_invites: number
  total_users: number
  active_teams: number
  usage_rate: number
  recent_activity: Array<{
    date: string
    invites: number
    redemptions: number
  }>
  status_breakdown: Record<string, number>
  mother_usage: Array<{
    id: number
    name: string
    seat_limit: number
    seats_used: number
    usage_rate: number
    status: string
  }>
  enabled_teams?: number
  max_code_capacity?: number
  active_codes?: number
  remaining_code_quota?: number
}

export interface CodeSkuSummary {
  id: number
  name: string
  slug: string
  description?: string | null
  lifecycle_days: number
  default_refresh_limit?: number | null
  price_cents?: number | null
  is_active: boolean
  created_at: string
  updated_at: string
}

export interface DbEngineStatus {
  ok: boolean
  url?: string | null
  dialect?: string | null
  alembic_version?: string | null
  error?: string | null
}

export interface ServiceStatusSnapshot {
  backend: 'online' | 'offline' | 'unknown'
  lastCheck: Date | null
  db?: {
    users?: DbEngineStatus
    pool?: DbEngineStatus
  }
}
